version: '3'
services:
  nginx-tes:
   image: nginx:latest
   volumes:
     - /var/lib/docker/volumes/volume-nginx:/usr/share/nginx/html
   ports:
     - "8088:80"
  httpd-tes:
    image: httpd:2.4.55-alpine
    volumes:
     - /var/lib/docker/volumes/volume-httpd:/var/www/html
    ports:
      - "8089:80"
