version: '3'
services:
  nginx-tes:
   image: fazler/nginx
   build: nginx/.
   ports:
     - "8088:80"
   volumes:
    - nginx-test:/usr/share/nginx/html
  httpd-tes:
    image: fazler/httpd
    build: apache/.
    ports:
      - "8089:80"
    volumes:
      - httpd-test:/usr/local/apache2/htdocs/
volumes:
  nginx-test:
  httpd-test:
