version: '3'
services:
  nginx-tes:
   image: webapp1/nginx
   build: ./nginx
   ports:
     - "8088:80"
   volumes:
    - nginx-test:/usr/share/nginx/html
  httpd-tes:
    image: webapp1/httpd
    build: ./nginx
    ports:
      - "8089:80"
    volumes:
      - httpd-test:/usr/local/apache2/htdocs/
volumes:
  nginx-test:
  httpd-test:
